micronaut:
  application:
    name: micronautWithLiquibase
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
    driverClassName: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
endpoints:
  liquibase:
    enabled: true
    sensitive: false


